const applications = [
  {
    studentEmail: "rahul.sharma@gmail.com",
    jobTitle: "Frontend Developer",
    company: "Infosys",
    status: "Pending",
  },
  {
    studentEmail: "sneha.reddy@gmail.com",
    jobTitle: "AI/ML Engineer",
    company: "Microsoft",
    status: "Accepted",
  },
  {
    studentEmail: "arjun.kumar@gmail.com",
    jobTitle: "Java Backend Developer",
    company: "TCS",
    status: "Pending",
  },
  {
    studentEmail: "aditi.sharma@gmail.com",
    jobTitle: "React Developer",
    company: "Accenture",
    status: "Accepted",
  },
  {
    studentEmail: "saikiran@gmail.com",
    jobTitle: "Python Developer",
    company: "Cognizant",
    status: "Rejected",
  },
  {
    studentEmail: "karthik.varma@gmail.com",
    jobTitle: "Software Development Engineer",
    company: "Amazon",
    status: "Pending",
  },
  {
    studentEmail: "pooja.nair@gmail.com",
    jobTitle: "Cloud Engineer",
    company: "Wipro",
    status: "Accepted",
  },
  {
    studentEmail: "vikram.singh@gmail.com",
    jobTitle: "Data Analyst",
    company: "Deloitte",
    status: "Pending",
  },
  {
    studentEmail: "neha.gupta@gmail.com",
    jobTitle: "Machine Learning Engineer",
    company: "Google",
    status: "Accepted",
  },
  {
    studentEmail: "rohit.verma@gmail.com",
    jobTitle: "Full Stack Developer",
    company: "Zoho",
    status: "Pending",
  },
  {
    studentEmail: "ananya.gupta@gmail.com",
    jobTitle: "Software Engineering Intern",
    company: "Google",
    status: "Accepted",
  },
  {
    studentEmail: "harsha.vardhan@gmail.com",
    jobTitle: "Node.js Developer",
    company: "Oracle",
    status: "Pending",
  },
  {
    studentEmail: "keerthana.rao@gmail.com",
    jobTitle: "Data Engineer",
    company: "Microsoft",
    status: "Pending",
  },
  {
    studentEmail: "nikhil.reddy@gmail.com",
    jobTitle: "Business Analyst",
    company: "Deloitte",
    status: "Rejected",
  },
  {
    studentEmail: "divya.priya@gmail.com",
    jobTitle: "UI/UX Designer",
    company: "Adobe",
    status: "Pending",
  },
  {
    studentEmail: "saiteja@gmail.com",
    jobTitle: "Software Engineer",
    company: "Zoho",
    status: "Accepted",
  },
  {
    studentEmail: "lavanya.sree@gmail.com",
    jobTitle: "QA Automation Engineer",
    company: "Capgemini",
    status: "Pending",
  },
  {
    studentEmail: "akhil.krishna@gmail.com",
    jobTitle: "Android Developer",
    company: "PhonePe",
    status: "Rejected",
  },
  {
    studentEmail: "meghana.patel@gmail.com",
    jobTitle: "DevOps Engineer",
    company: "IBM",
    status: "Accepted",
  },
  {
    studentEmail: "koushik.raju@gmail.com",
    jobTitle: "Software Development Engineer",
    company: "Amazon",
    status: "Pending",
  },
  {
    studentEmail: "rahul.sharma@gmail.com",
    jobTitle: "Cloud Engineer",
    company: "Wipro",
    status: "Accepted",
  },
  {
    studentEmail: "rahul.sharma@gmail.com",
    jobTitle: "Software Engineer",
    company: "Zoho",
    status: "Pending",
  },
  {
    studentEmail: "sneha.reddy@gmail.com",
    jobTitle: "Machine Learning Engineer",
    company: "Google",
    status: "Pending",
  },
  {
    studentEmail: "arjun.kumar@gmail.com",
    jobTitle: "Node.js Developer",
    company: "Oracle",
    status: "Accepted",
  },
  {
    studentEmail: "aditi.sharma@gmail.com",
    jobTitle: "Frontend Developer",
    company: "Infosys",
    status: "Pending",
  },
  {
    studentEmail: "saikiran@gmail.com",
    jobTitle: "Business Analyst",
    company: "Deloitte",
    status: "Pending",
  },
  {
    studentEmail: "karthik.varma@gmail.com",
    jobTitle: "Data Engineer",
    company: "Microsoft",
    status: "Accepted",
  },
  {
    studentEmail: "pooja.nair@gmail.com",
    jobTitle: "React Developer",
    company: "Accenture",
    status: "Pending",
  },
  {
    studentEmail: "vikram.singh@gmail.com",
    jobTitle: "Java Backend Developer",
    company: "TCS",
    status: "Rejected",
  },
  {
    studentEmail: "neha.gupta@gmail.com",
    jobTitle: "Software Engineering Intern",
    company: "Google",
    status: "Accepted",
  },
  {
    studentEmail: "rohit.verma@gmail.com",
    jobTitle: "Android Developer",
    company: "PhonePe",
    status: "Pending",
  },
  {
    studentEmail: "ananya.gupta@gmail.com",
    jobTitle: "Software Development Engineer",
    company: "Amazon",
    status: "Pending",
  },
  {
    studentEmail: "harsha.vardhan@gmail.com",
    jobTitle: "Python Developer",
    company: "Cognizant",
    status: "Accepted",
  },
  {
    studentEmail: "keerthana.rao@gmail.com",
    jobTitle: "AI/ML Engineer",
    company: "Microsoft",
    status: "Pending",
  },
  {
    studentEmail: "nikhil.reddy@gmail.com",
    jobTitle: "DevOps Engineer",
    company: "IBM",
    status: "Pending",
  },
  {
    studentEmail: "divya.priya@gmail.com",
    jobTitle: "Cloud Engineer",
    company: "Wipro",
    status: "Accepted",
  },
  {
    studentEmail: "saiteja@gmail.com",
    jobTitle: "Java Backend Developer",
    company: "TCS",
    status: "Pending",
  },
  {
    studentEmail: "lavanya.sree@gmail.com",
    jobTitle: "Software Engineer",
    company: "Zoho",
    status: "Rejected",
  },
  {
    studentEmail: "akhil.krishna@gmail.com",
    jobTitle: "Data Analyst",
    company: "Deloitte",
    status: "Pending",
  },
  {
    studentEmail: "meghana.patel@gmail.com",
    jobTitle: "AI/ML Engineer",
    company: "Microsoft",
    status: "Accepted",
  },
  {
    studentEmail: "koushik.raju@gmail.com",
    jobTitle: "React Developer",
    company: "Accenture",
    status: "Accepted",
  },
  {
    studentEmail: "rahul.sharma@gmail.com",
    jobTitle: "Data Analyst",
    company: "Deloitte",
    status: "Rejected",
  },
  {
    studentEmail: "sneha.reddy@gmail.com",
    jobTitle: "Software Development Engineer",
    company: "Amazon",
    status: "Accepted",
  },
  {
    studentEmail: "arjun.kumar@gmail.com",
    jobTitle: "Software Engineer",
    company: "Zoho",
    status: "Pending",
  },
  {
    studentEmail: "aditi.sharma@gmail.com",
    jobTitle: "Cloud Engineer",
    company: "Wipro",
    status: "Accepted",
  },
  {
    studentEmail: "saikiran@gmail.com",
    jobTitle: "Java Backend Developer",
    company: "TCS",
    status: "Pending",
  },
  {
    studentEmail: "karthik.varma@gmail.com",
    jobTitle: "AI/ML Engineer",
    company: "Microsoft",
    status: "Accepted",
  },
  {
    studentEmail: "pooja.nair@gmail.com",
    jobTitle: "Business Analyst",
    company: "Deloitte",
    status: "Pending",
  },
  {
    studentEmail: "vikram.singh@gmail.com",
    jobTitle: "Software Engineering Intern",
    company: "Google",
    status: "Accepted",
  },
  {
    studentEmail: "neha.gupta@gmail.com",
    jobTitle: "Node.js Developer",
    company: "Oracle",
    status: "Pending",
  },
  {
    studentEmail: "rohit.verma@gmail.com",
    jobTitle: "Machine Learning Engineer",
    company: "Google",
    status: "Rejected",
  },
  {
    studentEmail: "ananya.gupta@gmail.com",
    jobTitle: "Data Engineer",
    company: "Microsoft",
    status: "Accepted",
  },
  {
    studentEmail: "harsha.vardhan@gmail.com",
    jobTitle: "Frontend Developer",
    company: "Infosys",
    status: "Pending",
  },
  {
    studentEmail: "keerthana.rao@gmail.com",
    jobTitle: "QA Automation Engineer",
    company: "Capgemini",
    status: "Accepted",
  },
  {
    studentEmail: "nikhil.reddy@gmail.com",
    jobTitle: "Python Developer",
    company: "Cognizant",
    status: "Pending",
  },
  {
    studentEmail: "divya.priya@gmail.com",
    jobTitle: "Software Development Engineer",
    company: "Amazon",
    status: "Accepted",
  },
  {
    studentEmail: "saiteja@gmail.com",
    jobTitle: "Android Developer",
    company: "PhonePe",
    status: "Pending",
  },
  {
    studentEmail: "lavanya.sree@gmail.com",
    jobTitle: "React Developer",
    company: "Accenture",
    status: "Accepted",
  },
  {
    studentEmail: "akhil.krishna@gmail.com",
    jobTitle: "Cloud Engineer",
    company: "Wipro",
    status: "Pending",
  },
  {
    studentEmail: "meghana.patel@gmail.com",
    jobTitle: "Software Engineering Intern",
    company: "Google",
    status: "Accepted",
  },
];

export default applications;
