const jobs = [
  {
    title: "Frontend Developer",
    company: "Infosys",
    location: "Hyderabad",
    description:
      "Develop responsive web applications using React.js, JavaScript, HTML, CSS and REST APIs. Work closely with UI/UX designers and backend developers to build scalable enterprise applications.",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "REST API"],
    jobType: "Full-time",
    experience: "Fresher",
    recruiterEmail: "rahul.mehta@infosys.com",
  },
  {
    title: "Java Backend Developer",
    company: "TCS",
    location: "Bengaluru",
    description:
      "Build scalable backend services using Java, Spring Boot and MySQL. Develop REST APIs and optimize application performance.",
    salary: 750000,
    skills: ["Java", "Spring Boot", "MySQL", "REST API", "Git"],
    jobType: "Full-time",
    experience: "1 Year",
    recruiterEmail: "priya.sharma@tcs.com",
  },
  {
    title: "React Developer",
    company: "Accenture",
    location: "Pune",
    description:
      "Develop reusable React components, integrate APIs and improve application performance while working in Agile teams.",
    salary: 850000,
    skills: ["React", "Redux", "JavaScript", "Bootstrap", "Git"],
    jobType: "Full-time",
    experience: "Fresher",
    recruiterEmail: "ankit.verma@accenture.com",
  },
  {
    title: "Software Development Engineer",
    company: "Amazon",
    location: "Bengaluru",
    description:
      "Design scalable distributed systems, write clean code, review pull requests and participate in architecture discussions.",
    salary: 2200000,
    skills: ["Java", "AWS", "DSA", "Spring Boot", "SQL"],
    jobType: "Full-time",
    experience: "2 Years",
    recruiterEmail: "sneha.kapoor@amazon.com",
  },
  {
    title: "AI/ML Engineer",
    company: "Microsoft",
    location: "Hyderabad",
    description:
      "Build machine learning models, preprocess datasets and deploy AI solutions using Azure cloud services.",
    salary: 1800000,
    skills: ["Python", "TensorFlow", "Machine Learning", "Pandas", "NumPy"],
    jobType: "Full-time",
    experience: "2 Years",
    recruiterEmail: "karan.patel@microsoft.com",
  },
  {
    title: "Data Analyst",
    company: "Deloitte",
    location: "Chennai",
    description:
      "Analyze business datasets, prepare dashboards and generate reports using SQL, Power BI and Python.",
    salary: 800000,
    skills: ["SQL", "Power BI", "Excel", "Python", "Statistics"],
    jobType: "Full-time",
    experience: "Fresher",
    recruiterEmail: "neha.iyer@deloitte.com",
  },
  {
    title: "Python Developer",
    company: "Cognizant",
    location: "Hyderabad",
    description:
      "Develop backend services using Python and Django. Work with PostgreSQL and REST APIs.",
    salary: 700000,
    skills: ["Python", "Django", "PostgreSQL", "REST API", "Git"],
    jobType: "Full-time",
    experience: "1 Year",
    recruiterEmail: "arvind.rao@cognizant.com",
  },
  {
    title: "Cloud Engineer",
    company: "Wipro",
    location: "Hyderabad",
    description:
      "Maintain AWS cloud infrastructure, automate deployments and monitor cloud services.",
    salary: 900000,
    skills: ["AWS", "Docker", "Linux", "CI/CD", "Git"],
    jobType: "Full-time",
    experience: "1 Year",
    recruiterEmail: "meera.joshi@wipro.com",
  },
  {
    title: "Full Stack Developer",
    company: "Zoho",
    location: "Chennai",
    description:
      "Develop full stack web applications using React, Node.js and MongoDB. Collaborate with cross-functional teams.",
    salary: 950000,
    skills: ["React", "Node.js", "Express", "MongoDB", "JavaScript"],
    jobType: "Full-time",
    experience: "Fresher",
    recruiterEmail: "suresh.kumar@zoho.com",
  },
  {
    title: "Software Engineering Intern",
    company: "Google",
    location: "Hyderabad",
    description:
      "Work with Google engineering teams on production-level software projects while learning industry best practices.",
    salary: 80000,
    skills: ["C++", "Java", "DSA", "Problem Solving", "Git"],
    jobType: "Internship",
    experience: "Fresher",
    recruiterEmail: "pallavi.reddy@google.com",
  },
  {
    title: "DevOps Engineer",
    company: "IBM",
    location: "Bengaluru",
    description:
      "Develop CI/CD pipelines, automate deployments, and manage cloud infrastructure using Docker and Kubernetes.",
    salary: 1200000,
    skills: ["Docker", "Kubernetes", "Jenkins", "AWS", "Linux"],
    jobType: "Full-time",
    experience: "2 Years",
    recruiterEmail: "rahul.mehta@infosys.com",
  },
  {
    title: "Android Developer",
    company: "PhonePe",
    location: "Bengaluru",
    description:
      "Build high-performance Android applications using Kotlin and Jetpack libraries.",
    salary: 1600000,
    skills: ["Kotlin", "Android", "Firebase", "REST API", "Git"],
    jobType: "Full-time",
    experience: "1 Year",
    recruiterEmail: "priya.sharma@tcs.com",
  },
  {
    title: "Node.js Developer",
    company: "Oracle",
    location: "Hyderabad",
    description:
      "Develop scalable REST APIs using Node.js, Express and MongoDB for enterprise applications.",
    salary: 1100000,
    skills: ["Node.js", "Express", "MongoDB", "JWT", "REST API"],
    jobType: "Full-time",
    experience: "1 Year",
    recruiterEmail: "ankit.verma@accenture.com",
  },
  {
    title: "QA Automation Engineer",
    company: "Capgemini",
    location: "Pune",
    description:
      "Automate web application testing using Selenium and Java while ensuring software quality.",
    salary: 850000,
    skills: ["Java", "Selenium", "TestNG", "SQL", "Git"],
    jobType: "Full-time",
    experience: "1 Year",
    recruiterEmail: "sneha.kapoor@amazon.com",
  },
  {
    title: "Data Engineer",
    company: "Microsoft",
    location: "Hyderabad",
    description:
      "Design ETL pipelines and manage large-scale data processing using Azure Data Factory and SQL.",
    salary: 1900000,
    skills: ["Python", "SQL", "Azure", "Spark", "Data Engineering"],
    jobType: "Full-time",
    experience: "2 Years",
    recruiterEmail: "karan.patel@microsoft.com",
  },
  {
    title: "UI/UX Designer",
    company: "Adobe",
    location: "Noida",
    description:
      "Design modern, user-friendly interfaces and collaborate with developers to improve user experience.",
    salary: 900000,
    skills: ["Figma", "Adobe XD", "UI Design", "UX Research", "Prototyping"],
    jobType: "Full-time",
    experience: "Fresher",
    recruiterEmail: "neha.iyer@deloitte.com",
  },
  {
    title: "Cyber Security Analyst",
    company: "Wipro",
    location: "Hyderabad",
    description:
      "Monitor security events, identify vulnerabilities and implement security best practices.",
    salary: 1000000,
    skills: ["Network Security", "Linux", "SIEM", "Python", "Cyber Security"],
    jobType: "Full-time",
    experience: "1 Year",
    recruiterEmail: "meera.joshi@wipro.com",
  },
  {
    title: "Machine Learning Engineer",
    company: "Google",
    location: "Bengaluru",
    description:
      "Develop production-ready machine learning models and optimize inference performance.",
    salary: 2500000,
    skills: ["Python", "TensorFlow", "PyTorch", "Machine Learning", "Docker"],
    jobType: "Full-time",
    experience: "2 Years",
    recruiterEmail: "pallavi.reddy@google.com",
  },
  {
    title: "Software Engineer",
    company: "Zoho",
    location: "Chennai",
    description:
      "Develop scalable business software products using Java, JavaScript and SQL.",
    salary: 1000000,
    skills: ["Java", "JavaScript", "SQL", "Git", "Problem Solving"],
    jobType: "Full-time",
    experience: "Fresher",
    recruiterEmail: "suresh.kumar@zoho.com",
  },
  {
    title: "Business Analyst",
    company: "Deloitte",
    location: "Hyderabad",
    description:
      "Gather business requirements, analyze workflows and coordinate between stakeholders and technical teams.",
    salary: 850000,
    skills: ["Excel", "SQL", "Power BI", "Communication", "Business Analysis"],
    jobType: "Full-time",
    experience: "Fresher",
    recruiterEmail: "neha.iyer@deloitte.com",
  },
];

export default jobs;
