const users = [
  {
    name: "Rahul Sharma",
    email: "rahul.sharma@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500001",
      college: "Aditya Engineering College",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 8.9,
      skills: ["Java", "React", "SQL"],
      bio: "Passionate full stack developer.",
      github: "https://github.com/rahulsharma",
      linkedin: "https://linkedin.com/in/rahulsharma",
    },
  },

  {
    name: "Sneha Reddy",
    email: "sneha.reddy@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500002",
      college: "Aditya Engineering College",
      branch: "Artificial Intelligence & Machine Learning",
      graduationYear: 2027,
      cgpa: 9.1,
      skills: ["Python", "Machine Learning", "TensorFlow"],
      bio: "Interested in AI research and deep learning.",
      github: "https://github.com/snehareddy",
      linkedin: "https://linkedin.com/in/snehareddy",
    },
  },

  {
    name: "Arjun Kumar",
    email: "arjun.kumar@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500003",
      college: "Aditya Engineering College",
      branch: "Information Technology",
      graduationYear: 2027,
      cgpa: 8.4,
      skills: ["Java", "Spring Boot", "MySQL"],
      bio: "Backend developer with Java expertise.",
      github: "https://github.com/arjunkumar",
      linkedin: "https://linkedin.com/in/arjunkumar",
    },
  },

  {
    name: "Aditi Sharma",
    email: "aditi.sharma@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500004",
      college: "Aditya Engineering College",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 8.7,
      skills: ["React", "Node.js", "MongoDB"],
      bio: "MERN stack enthusiast.",
      github: "https://github.com/aditisharma",
      linkedin: "https://linkedin.com/in/aditisharma",
    },
  },

  {
    name: "Sai Kiran",
    email: "saikiran@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500005",
      college: "Aditya Engineering College",
      branch: "Electronics and Communication",
      graduationYear: 2027,
      cgpa: 8.2,
      skills: ["Python", "Embedded C", "IoT"],
      bio: "Interested in IoT and embedded systems.",
      github: "https://github.com/saikiran",
      linkedin: "https://linkedin.com/in/saikiran",
    },
  },

  {
    name: "Karthik Varma",
    email: "karthik.varma@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500006",
      college: "Aditya Engineering College",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 9.0,
      skills: ["C++", "DSA", "Java"],
      bio: "Competitive programmer.",
      github: "https://github.com/karthikvarma",
      linkedin: "https://linkedin.com/in/karthikvarma",
    },
  },

  {
    name: "Pooja Nair",
    email: "pooja.nair@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500007",
      college: "Aditya Engineering College",
      branch: "Information Technology",
      graduationYear: 2027,
      cgpa: 8.8,
      skills: ["JavaScript", "React", "CSS"],
      bio: "Frontend developer.",
      github: "https://github.com/poojanair",
      linkedin: "https://linkedin.com/in/poojanair",
    },
  },

  {
    name: "Vikram Singh",
    email: "vikram.singh@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500008",
      college: "Aditya Engineering College",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 8.5,
      skills: ["Java", "Spring Boot", "AWS"],
      bio: "Cloud enthusiast.",
      github: "https://github.com/vikramsingh",
      linkedin: "https://linkedin.com/in/vikramsingh",
    },
  },

  {
    name: "Neha Gupta",
    email: "neha.gupta@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500009",
      college: "Aditya Engineering College",
      branch: "Artificial Intelligence & Machine Learning",
      graduationYear: 2027,
      cgpa: 9.3,
      skills: ["Python", "NLP", "Deep Learning"],
      bio: "AI enthusiast.",
      github: "https://github.com/nehagupta",
      linkedin: "https://linkedin.com/in/nehagupta",
    },
  },

  {
    name: "Rohit Verma",
    email: "rohit.verma@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500010",
      college: "Aditya Engineering College",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 8.6,
      skills: ["React", "Node.js", "Express"],
      bio: "Full Stack Developer.",
      github: "https://github.com/rohitverma",
      linkedin: "https://linkedin.com/in/rohitverma",
    },
  },
  {
    name: "Ananya Gupta",
    email: "ananya.gupta@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500011",
      college: "VIT-AP University",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 9.2,
      skills: ["Java", "React", "MongoDB"],
      bio: "Passionate about full stack development.",
      github: "https://github.com/ananyagupta",
      linkedin: "https://linkedin.com/in/ananyagupta",
    },
  },
  {
    name: "Harsha Vardhan",
    email: "harsha.vardhan@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500012",
      college: "SRM University",
      branch: "Information Technology",
      graduationYear: 2027,
      cgpa: 8.4,
      skills: ["Python", "Django", "PostgreSQL"],
      bio: "Backend developer.",
      github: "https://github.com/harshavardhan",
      linkedin: "https://linkedin.com/in/harshavardhan",
    },
  },
  {
    name: "Keerthana Rao",
    email: "keerthana.rao@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500013",
      college: "GITAM University",
      branch: "AI & ML",
      graduationYear: 2027,
      cgpa: 9.0,
      skills: ["Python", "TensorFlow", "Pandas"],
      bio: "Machine learning enthusiast.",
      github: "https://github.com/keerthanarao",
      linkedin: "https://linkedin.com/in/keerthanarao",
    },
  },
  {
    name: "Nikhil Reddy",
    email: "nikhil.reddy@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500014",
      college: "KL University",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 8.8,
      skills: ["Java", "Spring Boot", "MySQL"],
      bio: "Java backend developer.",
      github: "https://github.com/nikhilreddy",
      linkedin: "https://linkedin.com/in/nikhilreddy",
    },
  },
  {
    name: "Divya Priya",
    email: "divya.priya@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500015",
      college: "Aditya Engineering College",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 9.1,
      skills: ["React", "Redux", "CSS"],
      bio: "Frontend developer.",
      github: "https://github.com/divyapriya",
      linkedin: "https://linkedin.com/in/divyapriya",
    },
  },
  {
    name: "Sai Teja",
    email: "saiteja@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500016",
      college: "JNTU Kakinada",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 8.5,
      skills: ["Node.js", "Express", "MongoDB"],
      bio: "MERN stack learner.",
      github: "https://github.com/saiteja",
      linkedin: "https://linkedin.com/in/saiteja",
    },
  },
  {
    name: "Lavanya Sree",
    email: "lavanya.sree@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500017",
      college: "Andhra University",
      branch: "Information Technology",
      graduationYear: 2027,
      cgpa: 8.9,
      skills: ["Java", "SQL", "React"],
      bio: "Interested in web technologies.",
      github: "https://github.com/lavanyasree",
      linkedin: "https://linkedin.com/in/lavanyasree",
    },
  },
  {
    name: "Akhil Krishna",
    email: "akhil.krishna@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500018",
      college: "Vignan University",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 8.7,
      skills: ["C++", "DSA", "Java"],
      bio: "Competitive programmer.",
      github: "https://github.com/akhilkrishna",
      linkedin: "https://linkedin.com/in/akhilkrishna",
    },
  },
  {
    name: "Meghana Patel",
    email: "meghana.patel@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500019",
      college: "BVRIT",
      branch: "AI & ML",
      graduationYear: 2027,
      cgpa: 9.4,
      skills: ["Python", "Scikit-Learn", "Machine Learning"],
      bio: "AI researcher in progress.",
      github: "https://github.com/meghanapatel",
      linkedin: "https://linkedin.com/in/meghanapatel",
    },
  },
  {
    name: "Koushik Raju",
    email: "koushik.raju@gmail.com",
    password: "Password@123",
    role: "student",
    profile: {
      phone: "9876500020",
      college: "Aditya Engineering College",
      branch: "Computer Science",
      graduationYear: 2027,
      cgpa: 8.3,
      skills: ["React", "Node.js", "Express", "MongoDB"],
      bio: "Aspiring software engineer.",
      github: "https://github.com/koushikraju",
      linkedin: "https://linkedin.com/in/koushikraju",
    },
  },
  {
    name: "Rahul Mehta",
    email: "rahul.mehta@infosys.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400001",
      companyName: "Infosys",
      designation: "Senior Talent Acquisition Specialist",
      companyWebsite: "https://www.infosys.com",
      companyDescription:
        "Infosys is a global leader in next-generation digital services and consulting.",
    },
  },
  {
    name: "Priya Sharma",
    email: "priya.sharma@tcs.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400002",
      companyName: "Tata Consultancy Services",
      designation: "HR Business Partner",
      companyWebsite: "https://www.tcs.com",
      companyDescription:
        "TCS provides IT services, consulting and business solutions across industries.",
    },
  },
  {
    name: "Ankit Verma",
    email: "ankit.verma@accenture.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400003",
      companyName: "Accenture",
      designation: "Technical Recruiter",
      companyWebsite: "https://www.accenture.com",
      companyDescription:
        "Accenture is a global professional services company specializing in digital, cloud and security.",
    },
  },
  {
    name: "Sneha Kapoor",
    email: "sneha.kapoor@amazon.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400004",
      companyName: "Amazon",
      designation: "University Recruiter",
      companyWebsite: "https://www.amazon.jobs",
      companyDescription:
        "Amazon builds innovative products and services at a global scale.",
    },
  },
  {
    name: "Karan Patel",
    email: "karan.patel@microsoft.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400005",
      companyName: "Microsoft",
      designation: "Talent Acquisition Manager",
      companyWebsite: "https://careers.microsoft.com",
      companyDescription:
        "Microsoft empowers every person and organization to achieve more.",
    },
  },
  {
    name: "Neha Iyer",
    email: "neha.iyer@deloitte.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400006",
      companyName: "Deloitte",
      designation: "Campus Hiring Lead",
      companyWebsite: "https://www.deloitte.com",
      companyDescription:
        "Deloitte provides consulting, audit, tax and advisory services worldwide.",
    },
  },
  {
    name: "Arvind Rao",
    email: "arvind.rao@cognizant.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400007",
      companyName: "Cognizant",
      designation: "Senior Recruiter",
      companyWebsite: "https://www.cognizant.com",
      companyDescription:
        "Cognizant helps clients modernize technology and transform experiences.",
    },
  },
  {
    name: "Meera Joshi",
    email: "meera.joshi@wipro.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400008",
      companyName: "Wipro",
      designation: "Recruitment Manager",
      companyWebsite: "https://www.wipro.com",
      companyDescription:
        "Wipro delivers innovative technology solutions and business consulting services.",
    },
  },
  {
    name: "Suresh Kumar",
    email: "suresh.kumar@zoho.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400009",
      companyName: "Zoho",
      designation: "Hiring Specialist",
      companyWebsite: "https://www.zoho.com",
      companyDescription:
        "Zoho develops cloud-based business software used by organizations around the world.",
    },
  },
  {
    name: "Pallavi Reddy",
    email: "pallavi.reddy@google.com",
    password: "Password@123",
    role: "recruiter",
    profile: {
      phone: "9123400010",
      companyName: "Google",
      designation: "University Programs Recruiter",
      companyWebsite: "https://careers.google.com",
      companyDescription:
        "Google builds products and technologies that organize the world's information.",
    },
  },
];

export default users;
